version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockers/web/Dockerfile
    container_name: django-app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    build:
      context: .
      dockerfile: dockers/db/Dockerfile
    container_name: django-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app_choice_db
      - POSTGRES_USER=admin-sys
      - POSTGRES_PASSWORD=linux
    ports:
      - "5432:5432"

volumes:
  postgres_data: